# Generated by Django 4.2.4 on 2023-10-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
    ]
