# Generated by Django 3.2.20 on 2023-07-12 11:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=200, verbose_name='фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='телефон')),
                ('product', models.ManyToManyField(related_name='orders', to='foodcartapp.Product', verbose_name='товар')),
            ],
        ),
    ]
