# Generated by Django 3.2.20 on 2023-07-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230713_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='foodcartapp.product', verbose_name='пункт заказа'),
            preserve_default=False,
        ),
    ]
