# Generated by Django 3.2.20 on 2023-07-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230713_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'пункт заказа', 'verbose_name_plural': 'пункты заказа'},
        ),
    ]
