# Generated by Django 3.2.20 on 2023-08-07 07:00

from django.db import migrations, models
import django.db.models.manager


def insert_cost(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'OrderProducts')
    for order in Order.objects.all():
        product_price = order.product.price
        order.cost = product_price * order.quantity
        order.save()


def pass_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('detail', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='cost',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name='Сумма по позиции заказа'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=insert_cost,
            reverse_code=pass_code,
        )
    ]
