# Generated by Django 3.2.20 on 2023-08-07 07:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('detail', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=8, verbose_name='Сумма по позиции заказа'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql=[("UPDATE OrderProducts AS op SET cost=product.price*op.quantity WHERE op.product=produck.pk and op.cost is null")],
            reverse_sql=[("ALTER TABLE OrderProducts DROP COLUMN cost")]
        )
    ]
