# Generated by Django 3.2.20 on 2023-08-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230807_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='orders',
                to='foodcartapp.product',
                verbose_name='пункт заказа'
            ),
            preserve_default=False,
        ),
    ]
