# Generated by Django 4.2.4 on 2023-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_orderproducts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('PRE', 'Собирается'), ('DLV', 'Готов к доставке'), ('DONE', 'Доставлен')], db_index=True, default='NEW', max_length=4, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='foodcartapp_phone_675d71_idx'),
        ),
    ]
