# Generated by Django 3.2.20 on 2023-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_orderproducts_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_datetime'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время поступления заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_datetime'], name='foodcartapp_order_d_7d4bad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='foodcartapp_phone_675d71_idx'),
        ),
    ]
