# Generated by Django 3.2.20 on 2023-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230813_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('PRE', 'Собирается'), ('DLV', 'Готов к доставке'), ('DONE', 'Доставлен')], default='NEW', max_length=4, verbose_name='Статус'),
        ),
    ]
