# Generated by Django 4.2.4 on 2023-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_comment_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='описание'),
        ),
    ]
