# Generated by Django 4.2.4 on 2023-08-30 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_ad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 30, 10, 21, 22, 651235, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
    ]
