# Generated by Django 3.2.20 on 2023-08-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('PRE', 'Собирается'), ('DLV', 'Готов к доставке'), ('DONE', 'Доставлен')], db_index=True, default='NEW', max_length=4, verbose_name='Статус'),
        ),
    ]
