# Generated by Django 4.2.4 on 2023-08-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_called_ad_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('EL', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='CASH', max_length=4, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 30, 10, 42, 25, 836502, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
    ]
