# Generated by Django 4.2.4 on 2023-09-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_managers_order_prepared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 9, 4, 18, 11, 41, 524581, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработан'), ('PRE', 'Готовится'), ('DLV', 'Доставляется'), ('DONE', 'Доставлен')], db_index=True, default='NEW', max_length=4, verbose_name='Статус'),
        ),
    ]
