# Generated by Django 4.2.4 on 2023-09-23 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_registrated_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 9, 23, 17, 7, 54, 615973, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
    ]
