# Generated by Django 4.2.4 on 2023-10-11 17:54

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


def copy_phonenumber(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        order.phonenumber = order.phone
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_rename_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=12, region=None, verbose_name='телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 10, 11, 17, 54, 17, 560651, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
        migrations.RunPython(copy_phonenumber),
    ]
