# Generated by Django 4.2.4 on 2023-10-11 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_phonenumber_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phone_675d71_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 10, 11, 18, 1, 32, 563424, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber'], name='foodcartapp_phonenu_5f4ceb_idx'),
        ),
    ]
