# Generated by Django 4.2.4 on 2023-10-12 13:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_comment_alter_order_registrated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 10, 12, 13, 17, 3, 527564, tzinfo=datetime.timezone.utc), verbose_name='дата и время поступления заказа'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='количество'),
        ),
    ]
